import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { db } from "../firebase/config";
import { doc, getDoc } from "firebase/firestore";

// Public page — no login needed — QR scan karne pe yeh dikhe
export default function EmergencyPublic() {
  const { uid } = useParams();
  const [card, setCard] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    getDoc(doc(db, "emergencyCards", uid))
      .then((snap) => {
        if (snap.exists()) setCard(snap.data());
        else setError(true);
        setLoading(false);
      })
      .catch(() => { setError(true); setLoading(false); });
  }, [uid]);

  if (loading) return (
    <div style={P.page}>
      <div style={P.center}>
        <div style={P.spinner} />
        <p style={P.loadText}>Loading emergency info...</p>
        <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
      </div>
    </div>
  );

  if (error || !card) return (
    <div style={P.page}>
      <div style={P.center}>
        <div style={{ fontSize: 48, marginBottom: 16 }}>⚠️</div>
        <p style={{ color: "rgba(255,255,255,0.6)", fontFamily: "'Space Grotesk',sans-serif" }}>Emergency card not found</p>
      </div>
    </div>
  );

  return (
    <div style={P.page}>
      <div style={P.orb1} />
      <div style={P.orb2} />

      <div style={P.container}>
        {/* Emergency header */}
        <div style={P.emergencyBanner}>
          <span style={P.emergencyIcon}>🚨</span>
          <div>
            <div style={P.emergencyTitle}>Emergency Medical Card</div>
            <div style={P.emergencySubtitle}>This person needs immediate assistance</div>
          </div>
        </div>

        {/* Main card */}
        <div style={P.card}>
          <div style={P.shimmer} />

          {/* User + blood group */}
          <div style={P.cardTop}>
            <div style={P.cardTopLeft}>
              <div style={P.bigBlood}>{card.bloodGroup || "—"}</div>
              <div style={P.bloodCaption}>Blood Group</div>
            </div>
            <div style={P.dividerV} />
            <div>
              <div style={P.infoLabel}>Patient</div>
              <div style={P.infoValue} id="patient-name">Emergency Card Holder</div>
              <div style={P.infoLabel} id="info-note" >Scan by medical personnel</div>
            </div>
          </div>

          {/* Info rows */}
          {[
            { icon: "⚠️", label: "Allergies", val: card.allergies },
            { icon: "📞", label: "Emergency Contact", val: card.emergencyContact ? `${card.emergencyContact}${card.emergencyPhone ? " — " + card.emergencyPhone : ""}` : null },
            { icon: "🏥", label: "Hospital / Doctor", val: [card.hospital, card.doctor].filter(Boolean).join(" — ") || null },
            { icon: "📋", label: "Medical Notes", val: card.medicalNotes },
          ].filter(({ val }) => val).map(({ icon, label, val }) => (
            <div key={label} style={P.infoRow}>
              <div style={P.rowIcon}>{icon}</div>
              <div>
                <div style={P.rowLabel}>{label}</div>
                <div style={P.rowVal}>{val}</div>
              </div>
            </div>
          ))}

          {/* Call button */}
          {card.emergencyPhone && (
            <a href={`tel:${card.emergencyPhone}`} style={P.callBtn}>
              📞 Call Emergency Contact — {card.emergencyPhone}
            </a>
          )}
        </div>

        <p style={P.footer}>Generated by The Final Handover · Secure Digital Vault</p>
      </div>
    </div>
  );
}

const P = {
  page: { minHeight: "100vh", background: "#07080f", fontFamily: "'Space Grotesk',sans-serif", position: "relative", overflow: "hidden", display: "flex", alignItems: "flex-start", justifyContent: "center" },
  orb1: { position: "fixed", top: -100, left: -80, width: 400, height: 400, background: "radial-gradient(circle,rgba(239,68,68,0.08) 0%,transparent 70%)", borderRadius: "50%", pointerEvents: "none" },
  orb2: { position: "fixed", bottom: -80, right: -60, width: 300, height: 300, background: "radial-gradient(circle,rgba(245,158,11,0.06) 0%,transparent 70%)", borderRadius: "50%", pointerEvents: "none" },
  center: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", minHeight: "100vh", gap: 16 },
  spinner: { width: 40, height: 40, border: "2px solid rgba(239,68,68,0.15)", borderTop: "2px solid #ef4444", borderRadius: "50%", animation: "spin 1s linear infinite" },
  loadText: { color: "rgba(255,255,255,0.3)", fontSize: 13, letterSpacing: "0.08em" },
  container: { width: "100%", maxWidth: 480, padding: "32px 20px 40px", position: "relative", zIndex: 1 },
  emergencyBanner: {
    display: "flex", alignItems: "center", gap: 14,
    background: "rgba(239,68,68,0.08)",
    border: "1px solid rgba(239,68,68,0.2)",
    borderRadius: 16, padding: "16px 20px", marginBottom: 16,
  },
  emergencyIcon: { fontSize: 28, flexShrink: 0 },
  emergencyTitle: { fontSize: 15, fontWeight: 700, color: "#f87171", letterSpacing: "0.02em" },
  emergencySubtitle: { fontSize: 11, color: "rgba(239,68,68,0.5)", marginTop: 3, letterSpacing: "0.04em" },
  card: {
    background: "linear-gradient(145deg,rgba(245,158,11,0.05),rgba(10,8,2,0.7))",
    border: "1px solid rgba(245,158,11,0.15)",
    borderRadius: 20, padding: 24, position: "relative", overflow: "hidden",
    boxShadow: "0 20px 60px rgba(0,0,0,0.5), 0 0 30px rgba(245,158,11,0.05)",
  },
  shimmer: { position: "absolute", top: 0, left: 0, right: 0, height: 1, background: "linear-gradient(90deg,transparent,rgba(245,158,11,0.5),transparent)" },
  cardTop: { display: "flex", alignItems: "center", gap: 20, paddingBottom: 20, marginBottom: 20, borderBottom: "1px solid rgba(255,255,255,0.05)" },
  cardTopLeft: { textAlign: "center", flexShrink: 0 },
  bigBlood: { fontSize: 42, fontWeight: 900, color: "#f87171", fontFamily: "'JetBrains Mono',monospace", lineHeight: 1, letterSpacing: "0.02em", textShadow: "0 0 20px rgba(239,68,68,0.3)" },
  bloodCaption: { fontSize: 9, color: "rgba(239,68,68,0.4)", textTransform: "uppercase", letterSpacing: "0.12em", marginTop: 4 },
  dividerV: { width: 1, height: 60, background: "rgba(255,255,255,0.06)", flexShrink: 0 },
  infoLabel: { fontSize: 9, color: "rgba(255,255,255,0.22)", textTransform: "uppercase", letterSpacing: "0.14em", marginBottom: 4 },
  infoValue: { fontSize: 15, fontWeight: 600, color: "rgba(255,255,255,0.88)" },
  infoRow: { display: "flex", alignItems: "flex-start", gap: 14, padding: "14px 0", borderBottom: "1px solid rgba(255,255,255,0.04)" },
  rowIcon: { fontSize: 20, flexShrink: 0, marginTop: 2 },
  rowLabel: { fontSize: 9, color: "rgba(255,255,255,0.22)", textTransform: "uppercase", letterSpacing: "0.12em", marginBottom: 5 },
  rowVal: { fontSize: 14, fontWeight: 500, color: "rgba(255,255,255,0.85)", lineHeight: 1.4 },
  callBtn: {
    display: "block", width: "100%", marginTop: 20,
    padding: "14px 20px", textAlign: "center",
    background: "linear-gradient(135deg,#ef4444,#b91c1c)",
    color: "white", textDecoration: "none",
    borderRadius: 14, fontSize: 14, fontWeight: 700,
    letterSpacing: "0.03em",
    boxShadow: "0 4px 20px rgba(239,68,68,0.3)",
  },
  footer: { textAlign: "center", fontSize: 10, color: "rgba(255,255,255,0.12)", marginTop: 24, letterSpacing: "0.06em" },
};
